[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--spec --cov=src --cov-report html"

[tool.flake8]
ignore = ["E203", "E266", "E501", "W503", "F403", "F401"]
max-line-length = 89
max-complexity = 18
select = ["B","C","E","F","W","T4","B9"]
